### ISSUE TITLE
c o n s i s t e n c y

### ISSUE THREAD

**Issue by tloth** [fac18/dynamyk-site#18]
Yay aria labels! Looks like you have had a great accessibility talk this week, or you were just born this way! :tada: 
To make your code even better, you could read through it, and add an aria label to all similar elements (e.g. the first section has an aria label, but none of the others do).

:frog:

**Comment by Oliversw** [comment]
I will also say though, that we want to be careful about overusing aria labels. They are designed to be used to communicate the purpose of an element on the page when it is not otherwise clear or defined. Definitely not saying that you should not do what the wonderful @tloth has suggested, but they can definitely easily be overused. If in doubt, use a screen reader extension to check whether the layout of your page makes sense to you!

**Comment by plasticneuron** [comment]
We went ahead with adding aria-labels to section elements because our heading structure is not the best, and to a couple of other appropriate places, but point taken about over-using. Thanks both of you!
